baseURL = 'https://wirestaq.com/'
languageCode = 'en-us'
title = 'Wirestaq'
theme = 'PaperMod'

[params]
    env = 'production'
    title = 'Wirestaq'
    description = 'Simplifying Agentic Workflows.'
    author = 'Wirestaq LLC'
    
    [params.homeInfoParams]
        Title = "Software that works."
        Content = "We build micro-SaaS products and custom software solutions for businesses that value simplicity and reliability."

    [[params.socialIcons]]
        name = 'github'
        url = 'https://github.com/joynahid'
    [[params.socialIcons]]
        name = 'twitter'
        url = 'https://x.com/quiteguy'

[menu]
    [[menu.main]]
        identifier = 'about'
        name = 'About'
        url = '/about'
        weight = 10
    [[menu.main]]
        identifier = 'privacy'
        name = 'Privacy'
        url = '/privacy'
        weight = 30
    [[menu.main]]
        identifier = 'terms'
        name = 'Terms'
        url = '/terms'
        weight = 40
